// pipelines_templates/CI_CD_Project/app_CD/Jenkinsfile
// GitOps CD pipeline for continuous deployment of Kubernetes manifests

pipeline {
    agent {
        docker {
            image "python:3.12-alpine"
            args '-u root:root --entrypoint='
        }
    }

    stages {
        stage('Checkout Manifests') {
            steps {
                checkout scm
            }
        }

        stage('Install Agent Dependencies') {
            when {
                expression { return (pipelineConfig.libraries?.kubernetes?.install_tools == true || pipelineConfig.libraries?.ansible?.install_tools == true) }
            }
            steps {
                k8sInstallTools()
            }
        }

        stage('Fetch Terraform Inventory') {
            steps {
                fetchInventory()
            }
        }

        stage('Deploy to DEV') {
            when {
                changeset "dev/**"
            }
            steps {
                echo "Changes detected in dev/ folder. Syncing DEV CLUSTER"
                input message: "Approve Deploying to DEV CLUSTER?", ok: "proceed"
                k8sDeploy(
                    namespace: 'weather-app',
                    target_folder: 'dev'
                )
            }
        }

        stage('Deploy to PROD') {
            when {
                changeset "prod/**"
            }
            steps {
                echo "Changes detected in prod/ folder. Syncing PROD CLUSTER"
                input message: "Approve Deploying to PROD CLUSTER?", ok: "proceed"
                k8sDeploy(
                    namespace: 'weather-app',
                    target_folder: 'prod'
                )
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo "CD Pipeline completed successfully. Clusters are synced with Git!"
        }
        failure {
            echo "CD Pipeline failed. Check the logs to see why kubectl rejected the YAML."
        }
    }
}