fields {
    required {
    }
    optional {
        repoUrl             = String    
        gitCreds            = String    
        terraformBranchName = String    

        infra_dir           = String    
        tf_vars             = String    

        cloud_creds         = String    

        ansible_dir         = String

        inventory_file      = String    // Ansible inventory file generated by Terraform (e.g. local_file resource). Default: 'inventory.ini'

        is_destroy          = Boolean   
        install_tools       = Boolean   

        softFail            = Boolean   
    }
}

steps {
    tfCheckoutCode
    tfInstallTools
    init
    validate
    checkov
    plan
    approval
    tfDeploy
    destroy
    archiveInventory
    terratest
}
